
import fs from 'fs'
const Layout = ''
const res = {
  code: 200,
  data: [
    {
      id: 200,
      parentId: 0,
      name: '质量管理',
      path: '/quality',
      component: null,
      icon: null,
      visible: true,
      keepAlive: true,
      children: [
        {
          id: 201,
          parentId: 200,
          name: '质控上报记录',
          path: 'inform',
          component: null,
          icon: null,
          visible: true,
          keepAlive: true,
          children: [
            {
              id: 202,
              parentId: 201,
              name: '一级质控',
              path: 'inform-l1',
              component: 'quality/informL1/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 203,
              parentId: 201,
              name: '二级质控',
              path: 'inform-l2',
              component: 'quality/informL2/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 204,
              parentId: 201,
              name: '三级质控',
              path: 'inform-l3',
              component: 'quality/informL3/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 205,
              parentId: 201,
              name: '夜查房评分记录',
              path: 'inform-night',
              component: 'quality/informNight/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
          ],
        },
        {
          id: 206,
          parentId: 200,
          name: '质控计划',
          path: 'plan',
          component: 'quality/plan/index',
          icon: null,
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 207,
          parentId: 200,
          name: '质控审核',
          path: 'audit',
          component: 'quality/audit/index',
          icon: null,
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 208,
          parentId: 200,
          name: '质控统计分析',
          path: 'stats',
          component: null,
          icon: null,
          visible: true,
          keepAlive: true,
          children: [
            {
              id: 209,
              parentId: 208,
              name: '一级护理质量巡查情况汇总表',
              path: 'stats-hlzlxc',
              component: 'quality/statsHlzlxc/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 210,
              parentId: 208,
              name: '二级护士素质检查情况汇总表',
              path: 'stats-hsszjc',
              component: 'quality/statsHsszjc/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
          ],
        },
        {
          id: 211,
          parentId: 200,
          name: '夜查房统计分析',
          path: 'nstats',
          component: null,
          icon: null,
          visible: true,
          keepAlive: true,
          children: [
            {
              id: 212,
              parentId: 211,
              name: '夜查房质控分登记表',
              path: 'nstats-hlzlxc',
              component: 'quality/nstatsZkfdj/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 213,
              parentId: 211,
              name: '夜查房质控分反馈表',
              path: 'nstats-hsszjc',
              component: 'quality/nstatsZkffk/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
          ],
        },
        {
          id: 214,
          parentId: 200,
          name: '统计报告',
          path: 'report',
          component: null,
          icon: null,
          visible: true,
          keepAlive: true,
          children: [
            {
              id: 215,
              parentId: 214,
              name: '一级质控报告',
              path: 'report-l1',
              component: 'quality/reportL1/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 216,
              parentId: 214,
              name: '二级质控报告',
              path: 'report-l2',
              component: 'quality/reportL2/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 217,
              parentId: 214,
              name: '三级质控报告',
              path: 'report-l3',
              component: 'quality/reportL3/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 218,
              parentId: 214,
              name: '夜查房报告',
              path: 'report-night',
              component: 'quality/reportNight/index',
              icon: null,
              visible: true,
              keepAlive: true,
              children: null,
            },
          ],
        },
        {
          id: 219,
          parentId: 200,
          name: '夜查房排班',
          path: 'nschedule',
          component: 'quality/nschedule/index',
          icon: null,
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 220,
          parentId: 200,
          name: '质控小组',
          path: 'group',
          component: 'quality/group/index',
          icon: null,
          visible: true,
          keepAlive: true,
          children: null,
        },
      ],
    },
  ],
  message: '',
}

// 遍历后台传来的路由字符串，转换为组件对象
function filterAsyncRouter(asyncRouterMap) {
  const hiddenBarMap = ['QCFormDetail', 'TemplateDesc', 'MessageCenter']
  const keyMap = {
    FirstQC: 'first_level_quality',
    SecondQC: 'second_level_quality',
    ThreeQC: 'three_level_quality',
    NIScoreRecord: 'night_check',
  }

  return asyncRouterMap?.map((route) => {
    // 质控上报记录

    const hasChildMenu = !!route.children
    return {
      path: `/${route.path}`,
      name: route.path,
      redirect: hasChildMenu ? `/${route.path}/${route.children[0].path}` : 'noRedirect',
      // component: route.component === 'Layout' ? Layout : () => import(`@/views${route.component}`),
      component: route.component === 'Layout' ? 'Layout' : `@/views/${route.component}`,
      alwaysShow: hasChildMenu ? true : undefined,
      hidden: !route.visible,
      children: filterAsyncRouter(route.children),
      meta: {
        title: route.name,
        noCache: true,
        affix: true,
        hiddenBar: hiddenBarMap.includes(route.path) ? true : undefined,
        key: keyMap[route.path],
      },
    }
  })
}

const target = filterAsyncRouter(res.data[0].children)
const fd = fs.openSync('./src/package/Promise/temp.json', 'w')

fs.writeSync(fd, JSON.stringify(target))
fs.closeSync(fd)
